### ISSUE TITLE
Error: invalid module name: 'exceptions'

### ISSUE THREAD

**Issue by datakurre** [plone/plone.recipe.zope2instance#105]
I have no idea why, but on a Python 3.7 setup I just got a startup error

```
Error: invalid module name: 'exceptions' (line 18, in file:///.../parts/instance/etc/zope.conf)
```

that when away when I changed

```
<warnfilter>
  action ignore
  category exceptions.DeprecationWarning
</warnfilter>
```

to 

```
<warnfilter>
  action ignore
  category DeprecationWarning
</warnfilter>
```

**Comment by dataflake** [comment]
That's not surprising. The recipe sets a bad import path there. I'm surprised no one has complained earlier, this has been in the code forever. PR on the way.
