### ISSUE TITLE
Deprecation Warning: makerequest

### ISSUE THREAD

**Issue by dhavlik** [plone/plone.recipe.zope2instance#122]
`makerequest` should be imported from `Testing.makerequest` instead of `Testing.ZopeTestCase.utils.makerequest`. Doing the latter also has a side effect: `ZOPETESTCASE` environment Variable is set to `"1"` whenever you import something from `Testing.ZopeTestCase`.
`makerequest` is also useful outside of test stuff.

**Comment by dataflake** [comment]
@icemac This appears done. The only reference I could find imports from the right place.

**Comment by icemac** [comment]
@dataflake The fix for this issue already seems to be in 6.4.0. Thank you for looking into this issue.
