### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by dataflake** [plone/plone.recipe.zope2instance#164]

**Comment by jugmac00** [comment]
Good luck! There seems to be a problem, which unfortunately was not specified...

https://github.com/plone/plone.recipe.zope2instance/commit/c11cd6efb3e9127e40379bbff7c20d91decbb06f

**Comment by dataflake** [comment]
For some reason the GitHub action this repo uses for CI didn't install `wheel` as prerequisite, which meant eggs containing C code were downloaded as tar balls and self-compiled. I saw failures during that self-compilation. It makes no sense to not use `wheel` and take advantage of pre-built binary eggs, and installing it solved GH test issues.
