### ISSUE TITLE
Enable adding custom "filters" to pipeline

### ISSUE THREAD

**Issue by jensens** [plone/plone.recipe.zope2instance#173]
It would be beneficial if one could provide one or more `[filter:CUSTOM]` sections to add and additional `CUSTOM` pipeline entries.

At the moment one needs to copy the `wsgi.ini` template and customize it, which overall is IMO to much effort for such a simple change.

**Comment by jensens** [comment]
ah sorry, just found this is a dup of #116 by  @ale-rt

**Comment by ale-rt** [comment]
Note I stopped completely working on #116 and #117. 
I see a little benefit in managing all the possible cases with this recipe so I actually end up using a template.
I also thought about starting something like `plone.recipe.wsgiinstance` to start with a cleaner code base, but then I just stopped :)

**Comment by jensens** [comment]
There are probably better ways. I'll see if I get your stuff running.
