### ISSUE TITLE
`build_wsgi_ini` should handle log file rotation in analogy with `build_zope_conf`

### ISSUE THREAD

**Issue by d-maurer** [plone/plone.recipe.zope2instance#179]
`recipe.Recipe.build_zope_conf` configures for use of the `RotatingFileHandler` when it sees rotating log options. `build_wsgi_ini` does not.

As a consequence, the rotation spec in the default Plone buildout configuration has not effect.

**Comment by ksuess** [comment]
For those stumbling over extending log files like me:
See "_Advanced logging options for WSGI_" in README.rst for changed configuration of log rotation with rotating handlers of `logging.handlers` when using wsgi.
