### ISSUE TITLE
NameError: name 'ZServerCtlOptions' is not defined when running a script and ZServer is not available

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.recipe.zope2instance#56]
When ZServer is not available and the wsgi parameter is omitted the class ZServerCtlOptions is not defined and an error is raised.

See also: https://github.com/plone/plone.staticresources/issues/4

**Comment by ale-rt** [comment]
@davisagli @tschorr do you think it is better to automatically set the wsgi parameter to True when ZServer is not available or it is better to exit with an informative message?

**Comment by davisagli** [comment]
What I want to do is make it default to wsgi when ZServer is gone and ZServer when it is there. If wsgi is explicitly set as on or off in python 2, use that. If it’s explicitly set as off in python 3, raise an exception. The tests will need some adjustment.

David Glick
(mobile)

**Comment by ale-rt** [comment]
I think this is already fixed in the meanwhile, at least my original issue is not reproducible anymore.
Thanks!
