### ISSUE TITLE
Support Python 2.7, 3.6, 3.7 as Plone 5.2 is doing

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.recipe.zope2instance#60]
See:

 -https://github.com/plone/plone.recipe.zope2instance/blob/a920a159c66576b16e74a304f8b41ac54d7e6749/.travis.yml

Also the tox conf and setup.py should be updated

**Comment by icemac** [comment]
@ale-rt Should the title of the issue better contain `3.6` instead of `3.5`?

**Comment by ale-rt** [comment]
Ops :) Fixed, thanks!
