### ISSUE TITLE
Add http-fast-listen option for WSGI setup

### ISSUE THREAD

**Issue by MrTango** [plone/plone.recipe.zope2instance#71]
It would be useable to have the http-fast-listen option also in a WSGI setup, so that the browser just waits until the server is up with the reload.

**Comment by pbauer** [comment]
gunicorn seems to support fast-listen. You can try it in coredev with `wsgioptions.cfg`.

Since waitress does not support this feature as far as I know you should add it as a feature-request in https://github.com/Pylons/waitress/issues.

**Comment by icemac** [comment]
This feature request also exists in zopefoundation/Zope#416.

**Comment by zopyx** [comment]
Aee also #74

**Comment by dataflake** [comment]
This issue can be closed. The option was implemented in #75 and the last remaining issue was resolved in #94 .
