### ISSUE TITLE
NameError: name 'ZServerCtlOptions' is not defined

### ISSUE THREAD

**Issue by zopyx** [plone/plone.recipe.zope2instance#74]
Version 6.1.1, Python 3:

```

bin/instance fg
Traceback (most recent call last):
  File "bin/instance", line 262, in <module>
    + sys.argv[1:]))
  File "/home/ajung/.buildout/eggs/plone.recipe.zope2instance-6.1.1-py3.7.egg/plone/recipe/zope2instance/ctl.py", line 883, in main
    options = ZServerCtlOptions()
NameError: name 'ZServerCtlOptions' is not defined
```

**Comment by frapell** [comment]
Also getting this when building a base Plone 5.2b1 with Python 3.7, when running bin/instance fg

**Comment by zopyx** [comment]
Tried with wsgi=on?

**Comment by zopyx** [comment]
And perhaps try the latest zope2instance checkout,from master

**Comment by frapell** [comment]
Oh, I was under the impression that wsgi was on by default... checking the commits I see the change was not yet released.

adding ```wsgi=on``` does fix the issue. thanks

**Comment by dataflake** [comment]
This is already fixed, `wsgi = on` is the default.
