### ISSUE TITLE
Update Plone docs for WSGI and Plone 5.2

### ISSUE THREAD

**Issue by pbauer** [plone/plone.recipe.zope2instance#77]
https://github.com/plone/documentation/blob/5.2/manage/upgrading/version_specific_migration/upgrade_to_52.rst needs a detailed section about the changes (or probably better: a link to a new page that has all this information).

Also there are sections in the docs where WSGI and ZServer is already mentioned and these need to be updated.
E.g.: 
https://docs.plone.org/manage/deploying/performance/tips.html#zserver-thread-count
https://docs.plone.org/manage/deploying/wsgi.html
https://docs.plone.org/manage/deploying/stack.html

**Comment by dataflake** [comment]
FWIW and maybe it helps you guys, I've done some local testing and put together a WSGI information page for the Zope documentation at https://zope.readthedocs.io/en/latest/wsgi.html

**Comment by Rudd-O** [comment]
@dataflake that page is 404.

**Comment by pbauer** [comment]
https://zope.readthedocs.io/en/latest/ has plenty of info on wsgi. A server not yet mentioned there is [pyruvate](https://pypi.org/project/pyruvate/)

**Comment by Rudd-O** [comment]
Thanks, P!
