### ISSUE TITLE
How to Modify the Home Page of Plone Website

### ISSUE THREAD

**Issue by dragonballhxf** [plone/plone.recipe.zope2instance#78]
How to Modify the Home Page of Plone Website?

**Comment by icemac** [comment]
Please see https://docs.plone.org especially https://docs.plone.org/working-with-content/managing-content/editing-content.html

**Comment by dragonballhxf** [comment]
icemac,thanks  you

**Comment by dragonballhxf** [comment]
If I want to make my own Plone skin, do you have any recommended tools? Thank you

**Comment by pbauer** [comment]
@dragonballhxf please post questions like these to http://community.plone.org.  For documentation please look at http://training.plone.org/ and http://docs.plone.org/
