### ISSUE TITLE
Release 6.1.5?

### ISSUE THREAD

**Issue by dataflake** [plone/plone.recipe.zope2instance#97]
There's several bug fixes and a feature added and I am actually referring to some of that stuff in the new Zope documentation. A release would be great. Thank you!

**Comment by gotcha** [comment]
I just made a release. https://pypi.org/project/plone.recipe.zope2instance/6.1.5. 
When `fullrelease` tries to push, I get :
```
INFO: remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
```

Sorry for not being aware of the new process.

**Comment by petschki** [comment]
I just got this too in another repo. Seems that the master branch protection by the github hooks (eg travis-ci hook etc.) prevents "non-repo-owners" to push commits to the master branch directly.
so the release process would be to ping @plone/release-team members who seems to have the permissions to directly commit to master ...

**Comment by petschki** [comment]
note: this is odd, but as a quick solution I've made a PR of the zest `postrelease` commits and merged it after the checks went through successfully (see https://github.com/collective/plone.formwidget.geolocation/pull/15)

**Comment by dataflake** [comment]
@gotcha Thank you Godefroid. Looks like even though the push failed, the new version 6.1.5 egg itself is "correct" on PyPI.

**Comment by mauritsvanrees** [comment]
The tag that @gotcha made got pushed correctly, so that is a start.

@gotcha Could you create a branch and PR with the changes you did? Then the history and everything should remain correct.
Actually, I have just added you as collaborator on this repo and given you admin rights. You should be able to push those changes directly to master now.

I am kinda hoping that those checks could be bypassed because all commits likely have `[ci skip]` in the commit message, but that would mean a too big loophole.

**Comment by gotcha** [comment]
@mauritsvanrees I was able to push. Thank you.

Are we in a situation where we need to get admin rights on any repo for which we want to do a release ? That would be odd.

**Comment by mauritsvanrees** [comment]
Yes, that would be odd.  But it would only be true for repositories that we have configured to require reviews.

**Comment by gotcha** [comment]
If we want to keep it this way, I suggest removing owners like me from PyPI or, maybe less radical, making a script that sets owners on PyPI as admin on those repos.

**Comment by gotcha** [comment]
I am not sure this is the right place to discuss those process issues. Where should it be done ?

**Comment by petschki** [comment]
definitely community.plone.org ... maybe mention the discussion here too: https://github.com/zestsoftware/zest.releaser/issues/325

**Comment by dataflake** [comment]
Closing because my initial question has been answered.
